name: Build CV PDF

on:
  push:
    branches:
      - main
    paths:
      - content/cv.md
      - content/cv-summary.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Pandoc & wkhtmltopdf
        run: sudo apt-get install -y pandoc wkhtmltopdf

      - name: Build CV PDF
        run: |
          { echo "# Gabriel Koerich | Software Engineer"; tail -n +5 content/cv.md | sed '/^## Notable Projects/,$d' | sed '/<!-- pdf:hide -->/,/<!-- \/pdf:hide -->/d' | sed 's/ <a [^>]*class="no-print"[^>]*>[^<]*<\/a>//g'; } > /tmp/cv-temp.md
          pandoc /tmp/cv-temp.md -o static/gabrielkoerich-cv.pdf \
            --from markdown+hard_line_breaks \
            --pdf-engine=wkhtmltopdf \
            -V margin-top=15mm \
            -V margin-bottom=15mm \
            -V margin-left=18mm \
            -V margin-right=18mm

      - name: Build CV Summary PDF
        run: |
          { echo "# Gabriel Koerich | Software Engineer"; tail -n +5 content/cv-summary.md | sed '/<!-- pdf:hide -->/,/<!-- \/pdf:hide -->/d' | sed 's/ <a [^>]*class="no-print"[^>]*>[^<]*<\/a>//g'; } > /tmp/cv-temp.md
          pandoc /tmp/cv-temp.md -o static/gabrielkoerich-cv-summary.pdf \
            --from markdown+hard_line_breaks \
            --pdf-engine=wkhtmltopdf \
            -V margin-top=15mm \
            -V margin-bottom=15mm \
            -V margin-left=18mm \
            -V margin-right=18mm

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Update CV PDF"
